# YOUR_HF_TOKEN_HERE: "YOUR_HF_TOKEN_HERE"        
# YOUR_HF_TOKEN_HERE: "moonshotai/Kimi-K2-Thinking:novita"


YOUR_HF_TOKEN_HERE: "YOUR_HF_TOKEN_HERE"        
YOUR_HF_TOKEN_HERE: "deepseek-ai/DeepSeek-V3.2-Exp:novita"